## docker file
FROM openjdk:8

## Author
LABEL maintainer="myapplicationsupport@company.com"

## Collect image build time arguments or use default
ARG app_artifact=airlinespringweb-0.0.1-SNAPSHOT
ARG app_context_root=airlinespringweb
ARG app_health_uri=isAlive
ARG app_health_patern="successful"
ARG app_name=airlinespringweb
ARG app_dir=/work/webapps/


# Environment Variables - declare with one ENV where possible
ENV LC_ALL en_US.UTF-8
ENV HEALTH_URI /${app_context_root}/${app_health_uri}
ENV HEALTH_PATTERN ${app_health_patern}

ENV JAVA_OPTS "-server -Xms256m -Xmx768m -XX:MetaspaceSize=72m -XX:MaxMetaspaceSize=256m -Dapp=${app_name} -Dapp.logdir=${app_dir}/tomcat/logs -Dspring.profiles.active=prod"

## create a folder for app image to prevent error in the startup
RUN mkdir -p ${app_dir}/app-lib;

## setup the exploded war directory for delivery
COPY target/${app_artifact} ${app_dir}/tomcat/${app_name}/

##chown [OPTIONS] USER[:GROUP] FILE(s)
# Ensure access to files by running user.
## switch user to root - this command works if the root is not set with any password
sudo su -
RUN chown -R webserver ${app_dir}

ENTRYPOINT ["java","${JAVA_OPTS}","-jar","${app_dir}/tomcat/${app_name}/${app_artifact}.war"]
